version: "3.1"

services:
  book_store:
    image: postgres:alpine3.20
    restart: "no"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: book_store
    networks:
      - book_store_backend
    ports:
      - 5432:5432
  book_api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - book_store_backend
    ports:
      - 8000:8000
    volumes:
      - ./:/app

networks:
  book_store_backend:
