version: "3.1"

services:
  book_store:
    image: postgres:alpine3.20
    restart: "no"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: book_store
    networks:
      - book_store_backend
    ports:
      - 5432:5432

networks:
  book_store_backend:
